nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']  # Replace with your React frontend URL
        allow_headers: ['Content-Type', 'Authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        expose_headers: []
        max_age: 3600
    paths:
        '^/api/':  # Apply CORS settings to all API routes
            allow_origin: ['http://localhost:3000']  # Replace with your React frontend URL
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
