security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: password

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                username_parameter: username
                password_parameter: password
            logout:
                path: /logout
                target: /
                invalidate_session: false
            remember_me:
                secret: '%env(APP_SECRET)%'
                lifetime: 604800 # 1 week
                path: /
                secure: auto

    