controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
signin:
    path: /signin
    controller: App\Controller\RegistrationController::login
    methods: POST